version: '3.7'

services:
  populate-mongo:
    profiles:
      - populate-mongo
    image: mongo:4.2
    volumes:
      - ./docker/config/graylog-config:/graylog-config
    working_dir: /graylog-config/
    networks:
      - localdev
    command:
      /graylog-config/graylog.sh

  mongo:
    platform: linux/arm64/v8
    profiles:
      - logger
    image: mongo:4.2
    networks:
      - localdev
    volumes:
      - mongo-data:/data/db

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    profiles:
      - logger
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 512mb
          cpus: "1.0"
    networks:
      - localdev
    ports:
      - "9222:9200"
    #volumes:
    #  - elasticsearch-data:/usr/share/elasticsearch/data

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    profiles:
      - logger
    image: graylog/graylog:4.1.2
    environment:
      # CHANGE ME (must be at least 16 characters)!
      # - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      # - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_PASSWORD_SECRET=12345hunter23456
      - GRAYLOG_ROOT_PASSWORD_SHA2=6b7f80513d5390b0c0a0532c1846a3f6aeba794913761045f714758893b6fdf1
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9500/ #admin:hunter23456
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - localdev
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    expose:
      - 9000
      - 1514
      - 1514/udp
      - 12201/udp
    ports:
      - "9500:9000"
      - "1514:1514"
      - "1514:1514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    #volumes:
    #  - graylog-data:/usr/share/graylog/data

volumes:
  mongo-data:
    driver: local
  elasticsearch-data:
    driver: local
  graylog-data:
    driver: local

networks:
  localdev:
    driver: bridge



