<?php declare(strict_types = 1);

namespace Everon\Logger\Configurator\Plugin;

use Everon\Logger\Configurator\AbstractArrayableConfigurator;
use InvalidArgumentException;
use UnexpectedValueException;
use function array_key_exists;
use function ctype_upper;
use function is_array;
use function is_object;
use function method_exists;
use function sprintf;
use function strtolower;
use function trim;

/**
 * Code generated by POPO generator, do not edit.
 * https://packagist.org/packages/popo/generator
 */
class GelfLoggerPluginSslOptions extends AbstractArrayableConfigurator
{
    protected array $data = [
        'verifyPeer' => true,
        'allowSelfSigned' => false,
        'caFile' => null,
        'ciphers' => null,
        'useSsl' => false,
    ];

    protected array $default = [
        'verifyPeer' => true,
        'allowSelfSigned' => false,
        'caFile' => null,
        'ciphers' => null,
        'useSsl' => false,
    ];

    protected array $propertyMapping = [
        'verifyPeer' => 'bool',
        'allowSelfSigned' => 'bool',
        'caFile' => 'string',
        'ciphers' => 'string',
        'useSsl' => 'bool',
    ];

    protected array $collectionItems = [
    ];

    protected array $updateMap = [];

    public function toArray(): array
    {
        $data = [];

        foreach ($this->propertyMapping as $key => $type) {
            if (!array_key_exists($key, $data)) {
                $data[$key] = $this->default[$key] ?? null;
            }
            $value = $this->data[$key];

            if ($this->isCollectionItem($key) && is_array($value)) {
                foreach ($value as $popo) {
                    if (is_object($popo) && method_exists($popo, 'toArray')) {
                        $data[$key][] = $popo->toArray();
                    }
                }

                continue;
            }

            if (is_object($value) && method_exists($value, 'toArray')) {
                $data[$key] = $value->toArray();
                continue;
            }

            $data[$key] = $value;
        }

        return $data;
    }

    protected function isCollectionItem(string $key): bool
    {
        return array_key_exists($key, $this->collectionItems);
    }

    public function fromArray(array $data): GelfLoggerPluginSslOptions
    {
        foreach ($this->propertyMapping as $key => $type) {
            $result[$key] = $this->default[$key] ?? null;

            if ($this->typeIsObject($type)) {
                $popo = new $this->propertyMapping[$key];
                if (method_exists($popo, 'fromArray')) {
                    $popoData = $data[$key] ?? $this->default[$key] ?? [];
                    $popo->fromArray($popoData);
                }
                $result[$key] = $popo;

                continue;
            }

            if (array_key_exists($key, $data)) {
                if ($this->isCollectionItem($key)) {
                    foreach ($data[$key] as $popoData) {
                        $popo = new $this->collectionItems[$key]();
                        if (method_exists($popo, 'fromArray')) {
                            $popo->fromArray($popoData);
                        }
                        $result[$key][] = $popo;
                    }
                }
                else {
                    $result[$key] = $data[$key];
                }
            }
        }

        $this->data = $result;

        foreach ($data as $key => $value) {
            if (!array_key_exists($key, $result)) {
                continue;
            }

            $type = $this->propertyMapping[$key] ?? null;
            if ($type !== null) {
                $value = $this->typecastValue($type, $result[$key]);
                $this->popoSetValue($key, $value);
            }
        }

        return $this;
    }

    /**
     * @param string $type
     * @param mixed $value
     *
     * @return mixed
     */
    protected function typecastValue(string $type, $value)
    {
        if ($value === null) {
            return $value;
        }

        switch ($type) {
            case 'int':
                $value = (int) $value;
                break;
            case 'string':
                $value = (string) $value;
                break;
            case 'bool':
                $value = (bool) $value;
                break;
            case 'array':
                $value = (array) $value;
                break;
        }

        return $value;
    }

    public function isNew(): bool
    {
        return empty($this->updateMap);
    }

    /**
     * @return boolean|null Enable certificate validation of remote party
     */
    public function verifyPeer(): ?bool
    {
        return $this->popoGetValue('verifyPeer');
    }

    /**
     * @param boolean|null $verifyPeer Enable certificate validation of remote party
     *
     * @return GelfLoggerPluginSslOptions
     */
    public function setVerifyPeer(?bool $verifyPeer): GelfLoggerPluginSslOptions
    {
        $this->popoSetValue('verifyPeer', $verifyPeer);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return boolean Enable certificate validation of remote party
     * @throws \UnexpectedValueException
     *
     */
    public function requireVerifyPeer(): bool
    {
        $this->assertPropertyValue('verifyPeer');

        return (bool) $this->popoGetValue('verifyPeer');
    }

    /**
     * @param string $property
     *
     * @return void
     * @throws UnexpectedValueException
     */
    protected function assertPropertyValue(string $property): void
    {
        if (!isset($this->data[$property])) {
            throw new UnexpectedValueException(sprintf(
                'Required value of "%s" has not been set',
                $property
            ));
        }
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasVerifyPeer(): bool
    {
        return $this->updateMap['verifyPeer'] ?? false;
    }

    /**
     * @return boolean|null Allow self-signed certificates
     */
    public function allowSelfSigned(): ?bool
    {
        return $this->popoGetValue('allowSelfSigned');
    }

    /**
     * @param boolean|null $allowSelfSigned Allow self-signed certificates
     *
     * @return GelfLoggerPluginSslOptions
     */
    public function setAllowSelfSigned(?bool $allowSelfSigned): GelfLoggerPluginSslOptions
    {
        $this->popoSetValue('allowSelfSigned', $allowSelfSigned);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return boolean Allow self-signed certificates
     * @throws \UnexpectedValueException
     *
     */
    public function requireAllowSelfSigned(): bool
    {
        $this->assertPropertyValue('allowSelfSigned');

        return (bool) $this->popoGetValue('allowSelfSigned');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasAllowSelfSigned(): bool
    {
        return $this->updateMap['allowSelfSigned'] ?? false;
    }

    /**
     * @return string|null Path to custom CA
     */
    public function getCaFile(): ?string
    {
        return $this->popoGetValue('caFile');
    }

    /**
     * @param string|null $caFile Path to custom CA
     *
     * @return GelfLoggerPluginSslOptions
     */
    public function setCaFile(?string $caFile): GelfLoggerPluginSslOptions
    {
        $this->popoSetValue('caFile', $caFile);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string Path to custom CA
     * @throws \UnexpectedValueException
     *
     */
    public function requireCaFile(): string
    {
        $this->assertPropertyValue('caFile');

        return (string) $this->popoGetValue('caFile');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasCaFile(): bool
    {
        return $this->updateMap['caFile'] ?? false;
    }

    /**
     * @return string|null List of ciphers the SSL layer may use. Formatted as specified in `ciphers(1)`
     */
    public function getCiphers(): ?string
    {
        return $this->popoGetValue('ciphers');
    }

    /**
     * @param string|null $ciphers List of ciphers the SSL layer may use. Formatted as specified in `ciphers(1)`
     *
     * @return GelfLoggerPluginSslOptions
     */
    public function setCiphers(?string $ciphers): GelfLoggerPluginSslOptions
    {
        $this->popoSetValue('ciphers', $ciphers);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return string List of ciphers the SSL layer may use. Formatted as specified in `ciphers(1)`
     * @throws \UnexpectedValueException
     *
     */
    public function requireCiphers(): string
    {
        $this->assertPropertyValue('ciphers');

        return (string) $this->popoGetValue('ciphers');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasCiphers(): bool
    {
        return $this->updateMap['ciphers'] ?? false;
    }

    /**
     * @return boolean|null Whenever to use Gelf\Transport\SslOptions
     */
    public function useSsl(): ?bool
    {
        return $this->popoGetValue('useSsl');
    }

    /**
     * @param boolean|null $useSsl Whenever to use Gelf\Transport\SslOptions
     *
     * @return GelfLoggerPluginSslOptions
     */
    public function setUseSsl(?bool $useSsl): GelfLoggerPluginSslOptions
    {
        $this->popoSetValue('useSsl', $useSsl);

        return $this;
    }

    /**
     * Throws exception if value is null.
     *
     * @return boolean Whenever to use Gelf\Transport\SslOptions
     * @throws \UnexpectedValueException
     *
     */
    public function requireUseSsl(): bool
    {
        $this->assertPropertyValue('useSsl');

        return (bool) $this->popoGetValue('useSsl');
    }

    /**
     * Returns true if value was set to any value, ignores defaults.
     *
     * @return bool
     */
    public function hasUseSsl(): bool
    {
        return $this->updateMap['useSsl'] ?? false;
    }

    /**
     * @param string $propertyName
     * @param mixed $value
     *
     * @return void
     * @throws \InvalidArgumentException
     */
    protected function addCollectionItem(string $propertyName, $value): void
    {
        $type = trim(strtolower($this->propertyMapping[$propertyName]));
        $collection = $this->popoGetValue($propertyName) ?? [];

        if (!is_array($collection) || $type !== 'array') {
            throw new InvalidArgumentException('Cannot add item to non array type: ' . $propertyName);
        }

        $collection[] = $value;

        $this->popoSetValue($propertyName, $collection);
    }

    /**
     * @param string $property
     *
     * @return mixed|null
     */
    protected function popoGetValue(string $property)
    {
        if (!isset($this->data[$property])) {
            if ($this->typeIsObject($this->propertyMapping[$property])) {
                $popo = new $this->propertyMapping[$property];
                $this->data[$property] = $popo;
            }
            else {
                return null;
            }
        }

        return $this->data[$property];
    }

    protected function typeIsObject(string $value): bool
    {
        return $value[0] === '\\' && ctype_upper($value[1]);
    }

    /**
     * @param string $property
     * @param mixed $value
     *
     * @return void
     */
    protected function popoSetValue(string $property, $value): void
    {
        $this->data[$property] = $value;

        $this->updateMap[$property] = true;
    }
}
